application: navtransoysteine

version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /?
  static_files: index.html
  upload: index.html

- url: /starry_night/?
  static_files: starry_night/index.html
  upload: starry_night/index.html

- url: /starry_night_results/?
  script: main.application

- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))  
