application: navtransoysteine

version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /
  script: main.application

- url: /.*/
  script: main.application

- url: /(.*/.*)
  static_files: \1
  upload: /(.*/.*)
